name: "CI"
on: [push, pull_request]
jobs:
    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run shellcheck
              run: |
                  sudo apt-get update -y
                  sudo apt-get install shellcheck
                  shellcheck reserver.sh
    linux:
        strategy:
            matrix:
                os: ["ubuntu-latest", "ubuntu-20.04", "ubuntu-18.04"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Run test on OS ${{ matrix.os }}
              env:
                  TERM: linux # fix tput for tty issue work around
                  RESERVER_DEBUG: true # prevent creating actual large files
              run: |
                  npm install -g bats
                  bash --version
                  bash -c "time bats test/test.bats"
