name: "CI"
on: [push, pull_request]
jobs:
    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run shellcheck
              run: |
                  sudo apt-get update -y
                  sudo apt-get install shellcheck
                  shellcheck reserver.sh
    linux:
        strategy:
            matrix:
                os: ["ubuntu-latest", "ubuntu-20.04"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup BATS
              run: |
                  npm install -g bats

                  wget https://github.com/bats-core/bats-assert/archive/master.zip -O assert.zip
                  unzip assert.zip
                  mv bats-assert-master/* test/test_helper/bats-assert/

                  wget https://github.com/bats-core/bats-file/archive/master.zip -O file.zip
                  unzip file.zip
                  mv bats-file-master/* test/test_helper/bats-file/
                  
                  wget https://github.com/bats-core/bats-support/archive/master.zip -O support.zip
                  unzip support.zip
                  mv bats-support-master/* test/test_helper/bats-support/
            - name: Run test on OS ${{ matrix.os }}
              env:
                  TERM: linux # fix tput for tty issue work around
                  RESERVER_DEBUG: true # prevent creating actual large files
              run: |
                  bash --version
                  bash -c "time bats test/test.bats"
