name: "CI"
on: [push, pull_request]
jobs:
    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run shellcheck
              run: |
                  shellcheck reserver.sh
    linux:
        strategy:
            matrix:
                os: ["ubuntu-latest", "ubuntu-20.04", "ubuntu-18.04"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup BATS
              uses: mig4/setup-bats@v1
              with:
                bats-version: 1.6.0
            - name: Setup BATS libs
              uses: brokenpip3/setup-bats-libs@0.1.0
              with:
                assert-path: ./test/test_helper/bats-assert
                file-path: ./test/test_helper/bats/file
                support-path: ./test/test_helper/bats/support
                detik-install: false
            - name: Run test on OS ${{ matrix.os }}
              env:
                  TERM: linux # fix tput for tty issue work around
                  RESERVER_DEBUG: true # prevent creating actual large files
              run: |
                  bash --version
                  bash -c "time bats test/test.bats"
